import re

def PatternCount(Text, Pattern):
	count = 0
	i = 0
	k = len(Pattern) # kmer
	while i <= len(Text) - k:
		curr =  Text[i: i + k]
		if curr  == Pattern:
			count += 1
		i += 1
	return count
	

pattern = "AGGCTTGAG"
text = "GAGGCTTGAGGCTTGTGTCGTCAGGCTTGAGGCTTGTAGGCTTGGGAGGCTTGACAAAGTAAATTGAACTCACCGTGAGGCTTGACCAGGCTTGGCCCAGGCTTGGCTAGGCTTGTATGAGGCTTGAGAAGGCTTGTACAGGCTTGTAGAGGCTTGAGGAGGCTTGCGAGGCTTGAGGCTTGAGGCTTGAAGGCTTGAGGCTTGCCCCGCTATCGCCGCAAAAGGCTTGCAGGCTTGCAAGGCTTGTATGTGAGGCTTGAGGCTTGGTAAGTGAGGCTTGAATAGGCTTGAGGCTTGACAGGCTTGCTAGGCTTGTAGGCTTGGGAGGCCAAAGGCTTGGTGGGGTAGGCTTGTTAGGCTTGAGGCTTGTCAAGGCTTGTAGGCTTGAGGCTTGAGTCGCATAGGCTTGAGGCTTGCACACAGGCTTGAGGCTTGAAGGCTTGAGGCTTGAGGCTTGCGTGAAAGGCTTGAAGGCTTGCAGGCTTGTGAAGGCTTGAGGCTTGAGGCTTGAGGCTTGAGGCTTGAGGCTTGAGGCTTGGGGAGGCTTGAGGCTTGAGGCTTGTTCTAGGCTTGATCTAGGCTTGAGGCTTGGGGAGGCTTGTGAAGGCTTGAGGCTTGCAGGCTTGAAGGCTTGAGGCTTGGAGGCTTGGTGAGGCTTGATTAACTGAGGCTTGAGGCTTGGTCAGGCTTGTAGGCTTGCTAAAGGCTTGTAGGCTTGAGGCTTGTTACCAGGCTTGCTTAGGCTTGGGTCGGCTGCAGGCTTGTTCGGGAGGCTTGTGGCAGGCTTGAAAGGCTTGCCCCCAGGCTTGAGGCTTGAAGGCTTGCCTCACAGGCTTGGCAGGCTTGAGGCTTGCTGCCAGGCTTGGGGTATAAAGGCTTGGAGGCTTGCTTAAAGGCTTGTTAGGCTTGCGAGGCTTGGAGGCTTGTTCAAAACGCCAGGATAGGCTTG"

count = PatternCount(text, pattern)
print("Pattern found: {}".format(count)) # => 31

# def PatternCountWithRegex (Text, Pattern): # does not account for overlapping
# 	return len(re.findall(Pattern, Text))

# count = PatternCountWithRegex(text, pattern)

# print("Pattern found with regex: {}".format(count))